{
 "title": "WaterStream Fleet Demo",
 "tags": [ "mqtt" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Messages Received",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(mqtt_proxy_publish_received[1m]))",
     "legendFormat": "received rate, msg/sec"
    },
    {
     "expr": "sum(mqtt_proxy_publish_received)",
     "legendFormat": "received total count"
    },
    {
     "expr": "sum(rate(mqtt_proxy_published_to_kafka[1m]))",
     "legendFormat": "kafka publish rate, msg/sec"
    },
    {
     "expr": "sum(mqtt_proxy_published_to_kafka)",
     "legendFormat": "kafka total publish count"
    }
   ]
  },
  {
   "title": "Clients",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(mqtt_proxy_clients_current)",
     "legendFormat": "connected clients"
    }
   ]
  },
  {
   "title": "WaterStream Broker Heap",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{job=\"waterstream-kafka\", area=\"heap\"}",
     "legendFormat": "Heap, bytes ({{instance}})"
    }
   ]
  },
  {
   "title": "Client Connections Details",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(mqtt_proxy_connect_received)",
     "legendFormat": "CONNECT received"
    },
    { "expr": "sum(mqtt_proxy_accept_sent)", "legendFormat": "ACCEPT sent" },
    {
     "expr": "sum(mqtt_proxy_inactive_clients_disconnected)",
     "legendFormat": "Inactive clients disconnected"
    },
    {
     "expr": "sum(mqtt_proxy_connections_closed)",
     "legendFormat": "connections closed"
    },
    {
     "expr": "sum(mqtt_proxy_disconnect_received)",
     "legendFormat": "DISCONNECT received"
    },
    {
     "expr": "sum(mqtt_proxy_connect_rejected)",
     "legendFormat": "connections rejected"
    },
    {
     "expr": "sum(mqtt_proxy_overloaded_clients_disconnected)",
     "legendFormat": "overloaded disconnected"
    }
   ]
  }
 ]
}