{
 "title": "Vehicles simulator",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Vehicles",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vehicle_simulator_vehicles_current",
     "legendFormat": "Current vehicles"
    },
    {
     "expr": "vehicle_simulator_vehicles_created",
     "legendFormat": "Vehicles created"
    },
    {
     "expr": "vehicle_simulator_vehicles_removed",
     "legendFormat": "Vehicles removed"
    }
   ]
  },
  {
   "title": "Vehicles debug",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vehicle_simulator_vehicle_no_routes_events",
     "legendFormat": "No Route events count"
    },
    {
     "expr": "vehicle_simulator_vehicle_arrive_events",
     "legendFormat": "Arrive events count"
    },
    {
     "expr": "vehicle_simulator_vehicle_updates",
     "legendFormat": "Vehicle updates count"
    },
    {
     "expr": "vehicle_simulator_route_requests",
     "legendFormat": "Route service requests"
    },
    {
     "expr": "vehicle_simulator_vehicle_init_errors",
     "legendFormat": "Vehicle init errors"
    },
    {
     "expr": "vehicle_simulator_vehicles_unsolicited_removals",
     "legendFormat": "Unsolicited removals"
    }
   ]
  },
  {
   "title": "MQTT Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vehicle_simulator_mqtt_connect_current",
     "legendFormat": "Current connections"
    }
   ]
  },
  {
   "title": "MQTT Connections Debug",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vehicle_simulator_mqtt_connect_attempts",
     "legendFormat": "Connection attempts"
    },
    {
     "expr": "vehicle_simulator_mqtt_connect_success",
     "legendFormat": "Connection success"
    },
    {
     "expr": "vehicle_simulator_mqtt_connect_failed",
     "legendFormat": "Connection failed"
    },
    {
     "expr": "vehicle_simulator_mqtt_connections_closed",
     "legendFormat": "Connections closed"
    },
    {
     "expr": "vehicle_simulator_mqtt_disconnect_sent",
     "legendFormat": "Disconnect sent"
    }
   ]
  },
  {
   "title": "MQTT Messages",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vehicle_simulator_mqtt_messages_sent",
     "legendFormat": "total count"
    },
    {
     "expr": "rate(vehicle_simulator_mqtt_messages_sent[1m])",
     "legendFormat": "rate, msg/sec"
    }
   ]
  },
  {
   "title": "Other debug",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vehicle_simulator_vehicles_registry_size"
    },
    {
     "expr": "vehicle_simulator_vehicles_registry_inserts"
    },
    {
     "expr": "vehicle_simulator_vehicles_registry_deletes"
    },
    {
     "expr": "vehicle_simulator_vehicles_registry_duplicate_plates"
    },
    {
     "expr": "vehicle_simulator_vehicles_registry_updates"
    }
   ]
  },
  {
   "title": "JVM",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_max{service=\"fleet-service\", area=\"heap\"}"
    },
    {
     "expr": "jvm_memory_bytes_used{service=\"fleet-service\"}"
    },
    {
     "expr": "sum(rate(jvm_gc_collection_seconds_sum{service=\"fleet-service\"}[1m]))",
     "legendFormat": "GC Time Fraction"
    }
   ]
  }
 ]
}